/* quiz_data2.c - topics 8-15 of the quiz bank. Split from quiz_data.c purely
 * to keep each file a readable length; the engine concatenates the two.
 */
#include <stddef.h>
#include "quiz.h"

const QItem QUIZ_BANK2[] = {
/* ------------------------------------------------------------ 8 Computing */
{8,0,"What does CPU stand for, first word?",{"central","core","computer","control"},0},
{8,0,"How many bits are in a byte?",{"four","six","eight","sixteen"},2},
{8,0,"What does WWW stand for, first word?",{"wide","world","web","wireless"},1},
{8,0,"Which company makes Windows?",{"Apple","Microsoft","Google","IBM"},1},
{8,0,"What device stores files permanently?",{"RAM","CPU","hard drive","monitor"},2},
{8,0,"What does a mouse control on screen?",{"cursor","volume","power","brightness"},0},
{8,1,"Which language is named after a snake?",{"Python","Cobra","Viper","Adder"},0},
{8,1,"What does HTML stand for, last word?",{"language","link","layer","list"},0},
{8,1,"How many bits in an IPv4 address?",{"16","32","64","128"},1},
{8,1,"What does SQL query?",{"files","databases","networks","images"},1},
{8,1,"Who is credited with the first computer program?",{"Turing","Lovelace","Babbage","Hopper"},1},
{8,1,"What does GPU stand for, first word?",{"general","graphics","global","grid"},1},
{8,2,"What is the time complexity of binary search?",{"O(1)","O(log n)","O(n)","O(n log n)"},1},
{8,2,"Which sort is stable and runs in O(n log n) worst case?",{"quicksort","heapsort","merge sort","bubble sort"},2},
{8,2,"What does TCP guarantee that UDP does not?",{"speed","delivery order","encryption","compression"},1},
{8,2,"In C, what does a pointer store?",{"a value","an address","a type","a size"},1},
{8,2,"What is the base of hexadecimal?",{"8","10","16","32"},2},
{8,2,"Which data structure is FIFO?",{"stack","queue","tree","heap"},1},
{8,3,"What does ACID stand for, first letter?",{"atomicity","access","alignment","allocation"},0},
{8,3,"Which problem is famously NP-complete?",{"sorting","shortest path","travelling salesman","matrix multiply"},2},
{8,3,"What does a hash collision mean?",{"two keys, one bucket","lost data","a crash","an overflow"},0},
{8,3,"Which paper introduced MapReduce?",{"Google, 2004","IBM, 1998","Yahoo, 2006","Amazon, 2007"},0},
{8,3,"What is tail recursion able to avoid?",{"stack growth","heap use","branching","caching"},0},
{8,3,"Which consensus algorithm underpins Raft's predecessor?",{"Paxos","Gossip","PBFT","Zab"},0},
/* ------------------------------------------------------------ 9 Mythology */
{9,0,"Who is the Greek king of the gods?",{"Apollo","Zeus","Hades","Ares"},1},
{9,0,"Which Norse god wields a hammer?",{"Odin","Loki","Thor","Baldr"},2},
{9,0,"What creature is half man, half horse?",{"centaur","minotaur","satyr","harpy"},0},
{9,0,"Who had hair made of snakes?",{"Circe","Medusa","Hera","Athena"},1},
{9,0,"Which Egyptian god has a jackal head?",{"Ra","Anubis","Horus","Thoth"},1},
{9,0,"What was Achilles' weak point?",{"knee","heel","wrist","neck"},1},
{9,1,"Who is the Roman equivalent of Zeus?",{"Mars","Jupiter","Neptune","Pluto"},1},
{9,1,"Which Greek hero completed twelve labours?",{"Perseus","Theseus","Heracles","Jason"},2},
{9,1,"What is the Norse end of the world called?",{"Valhalla","Ragnarok","Yggdrasil","Asgard"},1},
{9,1,"Who opened a jar releasing all evils?",{"Pandora","Persephone","Europa","Leda"},0},
{9,1,"Which river must the dead cross in Greek myth?",{"Lethe","Styx","Acheron","Cocytus"},1},
{9,1,"Which bird rises from its own ashes?",{"roc","phoenix","griffin","simurgh"},1},
{9,2,"Who is the Norse god of trickery?",{"Heimdall","Loki","Tyr","Freyr"},1},
{9,2,"Which Titan holds up the sky?",{"Cronus","Atlas","Prometheus","Oceanus"},1},
{9,2,"In Hindu myth, who is the preserver god?",{"Brahma","Vishnu","Shiva","Indra"},1},
{9,2,"What is the Japanese sun goddess called?",{"Izanami","Amaterasu","Inari","Benzaiten"},1},
{9,2,"Which Greek goddess sprang from Zeus's head?",{"Aphrodite","Athena","Artemis","Hestia"},1},
{9,2,"What is Yggdrasil in Norse myth?",{"a sword","a world tree","a ship","a wolf"},1},
{9,3,"Who ferries souls across the Styx?",{"Cerberus","Charon","Thanatos","Hypnos"},1},
{9,3,"Which Mesopotamian epic predates Homer?",{"Enuma Elish","Gilgamesh","Atrahasis","Erra"},1},
{9,3,"What are the Norns in Norse myth?",{"fates","valkyries","giants","dwarves"},0},
{9,3,"Which Celtic figure is the raven goddess of war?",{"Brigid","Morrigan","Danu","Epona"},1},
{9,3,"Who was punished with a boulder rolling forever?",{"Tantalus","Sisyphus","Ixion","Tityos"},1},
{9,3,"In Aztec myth, who is the feathered serpent?",{"Tezcatlipoca","Quetzalcoatl","Huitzilopochtli","Tlaloc"},1},
/* ------------------------------------------------------------------ 10 Art */
{10,0,"Who painted the Mona Lisa?",{"Michelangelo","Leonardo da Vinci","Raphael","Donatello"},1},
{10,0,"What are the three primary colours in paint?",{"red blue yellow","red green blue","cyan magenta yellow","black white grey"},0},
{10,0,"Which artist cut off part of his ear?",{"Monet","Van Gogh","Gauguin","Cezanne"},1},
{10,0,"What is a picture of a person called?",{"landscape","portrait","still life","mural"},1},
{10,0,"Which museum houses the Mona Lisa?",{"Prado","Louvre","Uffizi","Hermitage"},1},
{10,0,"What tool does a sculptor use on stone?",{"brush","chisel","loom","kiln"},1},
{10,1,"Who painted the Sistine Chapel ceiling?",{"Raphael","Michelangelo","Botticelli","Titian"},1},
{10,1,"Which movement is Monet associated with?",{"Cubism","Impressionism","Surrealism","Baroque"},1},
{10,1,"Who painted The Persistence of Memory?",{"Magritte","Dali","Miro","Ernst"},1},
{10,1,"What does fresco painting use as its surface?",{"canvas","wet plaster","wood","paper"},1},
{10,1,"Which artist is famous for soup cans?",{"Lichtenstein","Warhol","Rauschenberg","Johns"},1},
{10,1,"Who painted Guernica?",{"Dali","Picasso","Miro","Gris"},1},
{10,2,"Which technique uses strong light-dark contrast?",{"sfumato","chiaroscuro","impasto","glazing"},1},
{10,2,"Who painted Girl with a Pearl Earring?",{"Rembrandt","Vermeer","Hals","Steen"},1},
{10,2,"Cubism was founded by Picasso and whom?",{"Braque","Leger","Gris","Delaunay"},0},
{10,2,"Which movement did Kandinsky help start?",{"Fauvism","Abstract art","Dada","Futurism"},1},
{10,2,"What is a triptych?",{"a three-panel work","a three-colour work","a trio of artists","a sketch"},0},
{10,2,"Who sculpted The Thinker?",{"Rodin","Canova","Bernini","Giacometti"},0},
{10,3,"Which pigment was famously made from lapis lazuli?",{"vermilion","ultramarine","ochre","verdigris"},1},
{10,3,"Who painted The Garden of Earthly Delights?",{"Bruegel","Bosch","Van Eyck","Memling"},1},
{10,3,"What is pentimento?",{"an underlying earlier image","a varnish","a frame style","a brush"},0},
{10,3,"Which Japanese print style means 'pictures of the floating world'?",{"sumi-e","ukiyo-e","nihonga","yamato-e"},1},
{10,3,"Who founded the Bauhaus?",{"Mies van der Rohe","Gropius","Klee","Itten"},1},
{10,3,"Which artist pioneered drip painting?",{"Rothko","Pollock","De Kooning","Newman"},1},
/* --------------------------------------------------------------- 11 Nature */
{11,0,"What is the largest land animal?",{"rhino","hippo","elephant","giraffe"},2},
{11,0,"Which bird cannot fly?",{"eagle","penguin","swan","crow"},1},
{11,0,"What do bees make?",{"silk","honey","wax only","milk"},1},
{11,0,"How many legs does a spider have?",{"six","eight","ten","twelve"},1},
{11,0,"What is a baby frog called?",{"cub","tadpole","larva","fry"},1},
{11,0,"Which tree produces acorns?",{"oak","pine","birch","willow"},0},
{11,1,"What is the fastest land animal?",{"lion","cheetah","gazelle","horse"},1},
{11,1,"Which mammal lays eggs?",{"platypus","bat","sloth","otter"},0},
{11,1,"What is the largest species of shark?",{"great white","whale shark","tiger shark","basking shark"},1},
{11,1,"How long is an elephant's pregnancy, roughly?",{"9 months","12 months","18 months","22 months"},3},
{11,1,"Which animal has the longest migration?",{"grey whale","arctic tern","monarch","caribou"},1},
{11,1,"What is a group of lions called?",{"pack","pride","herd","troop"},1},
{11,2,"Which is the only continent without native ants?",{"Antarctica","Australia","Europe","Africa"},0},
{11,2,"What is the process by which plants make food?",{"respiration","photosynthesis","transpiration","germination"},1},
{11,2,"Which animal has the largest eye?",{"blue whale","giant squid","ostrich","elephant"},1},
{11,2,"What is a biome dominated by grass and few trees?",{"tundra","savanna","taiga","chaparral"},1},
{11,2,"Which insect order do beetles belong to?",{"Diptera","Coleoptera","Hymenoptera","Lepidoptera"},1},
{11,2,"What does an obligate carnivore require?",{"only meat","only plants","both","neither"},0},
{11,3,"What is the study of tree rings called?",{"palynology","dendrochronology","petrology","limnology"},1},
{11,3,"Which animal has the strongest bite force?",{"lion","saltwater crocodile","hyena","hippo"},1},
{11,3,"What is a keystone species?",{"the largest","one holding the ecosystem together","the rarest","the fastest"},1},
{11,3,"Which plant family do tomatoes belong to?",{"Rosaceae","Solanaceae","Brassicaceae","Fabaceae"},1},
{11,3,"What is the term for animals active at dusk?",{"nocturnal","diurnal","crepuscular","cathemeral"},2},
{11,3,"Which bird has the largest wingspan?",{"condor","wandering albatross","pelican","marabou"},1},
/* ---------------------------------------------------------------- 12 Space */
{12,0,"Which planet do we live on?",{"Mars","Earth","Venus","Jupiter"},1},
{12,0,"What orbits the Earth?",{"the Sun","the Moon","Mars","Venus"},1},
{12,0,"Which planet is known as the red planet?",{"Venus","Mars","Mercury","Saturn"},1},
{12,0,"What is at the centre of our solar system?",{"Earth","the Moon","the Sun","Jupiter"},2},
{12,0,"Which planet has obvious rings?",{"Jupiter","Saturn","Neptune","Mars"},1},
{12,0,"What is a shooting star really?",{"a star","a meteor","a planet","a comet"},1},
{12,1,"How many planets are in the solar system?",{"seven","eight","nine","ten"},1},
{12,1,"Which is the largest planet?",{"Saturn","Jupiter","Neptune","Uranus"},1},
{12,1,"What galaxy do we live in?",{"Andromeda","Milky Way","Triangulum","Sombrero"},1},
{12,1,"How long does light from the Sun take to reach Earth?",{"8 seconds","8 minutes","8 hours","8 days"},1},
{12,1,"Which planet is hottest?",{"Mercury","Venus","Mars","Jupiter"},1},
{12,1,"What was the first artificial satellite?",{"Explorer 1","Sputnik 1","Vanguard","Telstar"},1},
{12,2,"What is a light year a measure of?",{"time","distance","brightness","mass"},1},
{12,2,"Which force keeps planets in orbit?",{"magnetism","gravity","friction","inertia"},1},
{12,2,"What is the boundary of a black hole called?",{"singularity","event horizon","accretion disc","photon sphere"},1},
{12,2,"Which planet has the most moons currently known?",{"Jupiter","Saturn","Uranus","Neptune"},1},
{12,2,"What is the asteroid belt between?",{"Earth and Mars","Mars and Jupiter","Jupiter and Saturn","Venus and Earth"},1},
{12,2,"Which telescope launched in 1990?",{"Kepler","Hubble","Spitzer","Chandra"},1},
{12,3,"What is the Chandrasekhar limit about?",{"white dwarf mass","black hole size","star age","galaxy mass"},0},
{12,3,"Which type of star is the Sun?",{"red giant","G-type main sequence","white dwarf","blue supergiant"},1},
{12,3,"What causes a type Ia supernova?",{"core collapse","white dwarf accretion","neutron merger","hypernova"},1},
{12,3,"What does redshift indicate about a galaxy?",{"it is approaching","it is receding","it is hot","it is old"},1},
{12,3,"Which probe left the solar system first?",{"Pioneer 10","Voyager 1","Voyager 2","New Horizons"},1},
{12,3,"What is the cosmic microwave background?",{"starlight","afterglow of the Big Bang","dust","radio noise"},1},
/* ----------------------------------------------------------------- 13 Food */
{13,0,"What grain is bread usually made from?",{"rice","wheat","oats","barley"},1},
{13,0,"Which fruit is yellow and curved?",{"apple","banana","pear","plum"},1},
{13,0,"What is the main ingredient of guacamole?",{"pea","avocado","courgette","lime"},1},
{13,0,"Which drink is made from crushed grapes?",{"cider","wine","beer","whisky"},1},
{13,0,"What animal does bacon come from?",{"cow","pig","sheep","goat"},1},
{13,0,"Which vegetable makes you cry when cut?",{"carrot","onion","potato","turnip"},1},
{13,1,"Which country is sushi from?",{"China","Japan","Korea","Thailand"},1},
{13,1,"What spice is the most expensive by weight?",{"vanilla","saffron","cardamom","cinnamon"},1},
{13,1,"Which cheese is traditionally on a Greek salad?",{"cheddar","feta","brie","gouda"},1},
{13,1,"What is tofu made from?",{"soy beans","rice","wheat","chickpeas"},0},
{13,1,"Which nut is used in pesto traditionally?",{"almond","pine nut","walnut","cashew"},1},
{13,1,"What does 'al dente' describe?",{"firm to the bite","overcooked","raw","spicy"},0},
{13,2,"Which acid gives lemons their sourness?",{"acetic","citric","lactic","malic"},1},
{13,2,"What is the Maillard reaction responsible for?",{"browning","rising","curdling","fermenting"},0},
{13,2,"Which country originated the croissant's ancestor?",{"France","Austria","Italy","Belgium"},1},
{13,2,"What is umami?",{"a savoury taste","a texture","a spice","a cooking method"},0},
{13,2,"Which part of the plant is cinnamon?",{"root","bark","seed","flower"},1},
{13,2,"What makes bread rise?",{"salt","yeast","sugar","oil"},1},
{13,3,"Which mould ripens blue cheese?",{"Aspergillus","Penicillium","Rhizopus","Mucor"},1},
{13,3,"What is sous-vide cooking?",{"in a vacuum bath","over coals","in a pressure cooker","in a wok"},0},
{13,3,"Which grain is used for traditional sake?",{"barley","rice","millet","corn"},1},
{13,3,"What is the emulsifier in egg yolk?",{"albumin","lecithin","casein","pectin"},1},
{13,3,"Which pepper measures zero on the Scoville scale?",{"jalapeno","bell pepper","poblano","banana pepper"},1},
{13,3,"What is garum, used in Roman cooking?",{"fish sauce","olive paste","wine syrup","goat cheese"},0},
/* ------------------------------------------------------------- 14 Language */
{14,0,"How many letters are in the English alphabet?",{"24","25","26","27"},2},
{14,0,"What is the plural of 'mouse' (the animal)?",{"mouses","mice","mouse","mices"},1},
{14,0,"Which language is spoken in Brazil?",{"Spanish","Portuguese","French","Italian"},1},
{14,0,"What punctuation ends a question?",{"period","comma","question mark","colon"},2},
{14,0,"Which word is a noun?",{"quickly","happiness","run","blue"},1},
{14,0,"What language is 'hola' a greeting in?",{"Italian","Spanish","French","German"},1},
{14,1,"What is a word that sounds the same but differs in meaning?",{"synonym","homophone","antonym","acronym"},1},
{14,1,"Which language has the most native speakers?",{"English","Spanish","Mandarin","Hindi"},2},
{14,1,"What is the study of word origins called?",{"phonetics","etymology","syntax","semantics"},1},
{14,1,"Which alphabet does Russian use?",{"Latin","Cyrillic","Greek","Arabic"},1},
{14,1,"What is a palindrome?",{"reads the same backwards","has no vowels","is very long","is borrowed"},0},
{14,1,"How many cases does modern German have?",{"two","three","four","six"},2},
{14,2,"Which language family does Finnish belong to?",{"Indo-European","Uralic","Turkic","Altaic"},1},
{14,2,"What is a morpheme?",{"smallest unit of meaning","a sound","a sentence","a letter"},0},
{14,2,"Which writing system is logographic?",{"Korean","Chinese","Greek","Hebrew"},1},
{14,2,"What does SVO describe?",{"word order","a tense","a mood","a case"},0},
{14,2,"Which language is an official language of the UN but not Indo-European?",{"Russian","Arabic","Spanish","French"},1},
{14,2,"What is code-switching?",{"alternating languages","inventing words","translating","whispering"},0},
{14,3,"What is the ergative case used to mark?",{"subject of a transitive verb","possession","location","time"},0},
{14,3,"Which language has no irregular verbs by design?",{"Esperanto","Latin","Basque","Welsh"},0},
{14,3,"What is a phoneme?",{"a meaningful sound unit","a written letter","a syllable","a word"},0},
{14,3,"Which sound change turned Latin 'p' into Germanic 'f'?",{"Grimm's Law","Verner's Law","Grassmann's Law","Bartholomae's Law"},0},
{14,3,"What does the Sapir-Whorf hypothesis concern?",{"language and thought","sound change","grammar trees","translation"},0},
{14,3,"Which script was deciphered using the Behistun inscription?",{"hieroglyphs","cuneiform","Linear B","Brahmi"},1},
/* ----------------------------------------------------------- 15 Inventions */
{15,0,"Who is credited with inventing the telephone?",{"Edison","Bell","Marconi","Tesla"},1},
{15,0,"What did the Wright brothers invent?",{"the car","the aeroplane","the rocket","the balloon"},1},
{15,0,"What does a compass point to?",{"south","north","east","west"},1},
{15,0,"Which invention lets you see distant things?",{"microscope","telescope","periscope","kaleidoscope"},1},
{15,0,"What is used to tell the time on the wrist?",{"clock","watch","timer","sundial"},1},
{15,0,"Who invented the light bulb's practical form?",{"Edison","Faraday","Volta","Ampere"},0},
{15,1,"Who invented the printing press in Europe?",{"Caxton","Gutenberg","Manutius","Plantin"},1},
{15,1,"What year was the World Wide Web proposed?",{"1979","1989","1995","1999"},1},
{15,1,"Who developed the polio vaccine in 1955?",{"Pasteur","Salk","Fleming","Koch"},1},
{15,1,"What did Marconi pioneer?",{"radio","television","telephone","radar"},0},
{15,1,"Who discovered penicillin?",{"Lister","Fleming","Florey","Chain"},1},
{15,1,"What powers a photovoltaic cell?",{"heat","light","wind","pressure"},1},
{15,2,"Which invention is attributed to Johannes Kepler's contemporary Galileo?",{"improved telescope","microscope","barometer","thermometer"},0},
{15,2,"Who patented the first practical steam engine improvement?",{"Newcomen","Watt","Trevithick","Stephenson"},1},
{15,2,"What did Charles Babbage design but not finish?",{"Analytical Engine","Enigma","Turing machine","Colossus"},0},
{15,2,"Which material did Bakelite pioneer?",{"synthetic plastic","synthetic rubber","glass fibre","alloy steel"},0},
{15,2,"Who invented the cotton gin?",{"Whitney","Slater","Cartwright","Arkwright"},0},
{15,2,"What did Nikola Tesla champion for power distribution?",{"direct current","alternating current","static","battery"},1},
{15,3,"Which company built the first commercial microprocessor?",{"Intel","Motorola","TI","AMD"},0},
{15,3,"Who invented the Jacquard loom's punched card system?",{"Jacquard","Vaucanson","Bouchon","Falcon"},0},
{15,3,"What did Wilhelm Roentgen discover in 1895?",{"radioactivity","X-rays","the electron","the neutron"},1},
{15,3,"Which invention made long-distance electric lighting practical?",{"transformer","dynamo","capacitor","resistor"},0},
{15,3,"Who devised the first successful vulcanisation process?",{"Goodyear","Dunlop","Michelin","Firestone"},0},
{15,3,"What was ENIAC primarily built to compute?",{"census data","artillery tables","weather","payroll"},1},
{0,0,NULL,{NULL,NULL,NULL,NULL},0}
};

const int QUIZ_BANK2_COUNT = (int)(sizeof(QUIZ_BANK2) / sizeof(QUIZ_BANK2[0])) - 1;
