/* quiz_data.c - the question bank for the quiz family.
 *
 * Sixteen topics at four difficulty bands, six questions each. The bands are
 * genuinely graded: band 0 is common knowledge, band 3 is specialist. That is
 * what makes "easy" and "expert" separate catalogue entries rather than the
 * same questions with a shorter timer.
 *
 * Fields: topic, level, question, four answers, index of the correct one.
 */
#include <stddef.h>
#include "quiz.h"

const char *QUIZ_TOPIC[QUIZ_TOPICS] = {
    "General Knowledge", "Geography", "History", "Science", "Film", "Music",
    "Sport", "Literature", "Computing", "Mythology", "Art", "Nature",
    "Space", "Food", "Language", "Inventions"
};

const QItem QUIZ_BANK[] = {
/* ---------------------------------------------------- 0 General Knowledge */
{0,0,"How many sides does a hexagon have?",{"five","six","seven","eight"},1},
{0,0,"What colour do you get mixing blue and yellow?",{"green","purple","orange","brown"},0},
{0,0,"How many minutes are in an hour?",{"30","45","60","100"},2},
{0,0,"Which animal is known as man's best friend?",{"cat","dog","horse","cow"},1},
{0,0,"How many days are in a leap year?",{"364","365","366","367"},2},
{0,0,"What is the largest ocean?",{"Atlantic","Indian","Arctic","Pacific"},3},
{0,1,"How many strings does a standard violin have?",{"four","five","six","seven"},0},
{0,1,"What is the chemical symbol for gold?",{"Go","Au","Ag","Gd"},1},
{0,1,"How many players are on a netball team?",{"five","six","seven","eleven"},2},
{0,1,"Which planet is closest to the Sun?",{"Venus","Earth","Mercury","Mars"},2},
{0,1,"What is the tallest breed of dog?",{"Great Dane","Mastiff","Irish Wolfhound","St Bernard"},2},
{0,1,"How many degrees in a right angle?",{"45","90","180","360"},1},
{0,2,"What is the smallest prime number?",{"0","1","2","3"},2},
{0,2,"Which vitamin does the skin make from sunlight?",{"A","B12","C","D"},3},
{0,2,"What is the study of fungi called?",{"mycology","ichthyology","etymology","oncology"},0},
{0,2,"How many hearts does an octopus have?",{"one","two","three","four"},2},
{0,2,"What is the hardest natural substance?",{"quartz","diamond","corundum","topaz"},1},
{0,2,"Which gas makes up most of Earth's atmosphere?",{"oxygen","carbon dioxide","nitrogen","argon"},2},
{0,3,"What is a group of crows called?",{"a murder","a parliament","a murmuration","a gaggle"},0},
{0,3,"Which element has atomic number 79?",{"silver","platinum","gold","mercury"},2},
{0,3,"What does the acronym LASER stand for, first word?",{"light","linear","local","layered"},0},
{0,3,"What is the only letter not in any US state name?",{"J","Q","X","Z"},1},
{0,3,"Which unit measures sound intensity?",{"hertz","decibel","lumen","newton"},1},
{0,3,"What is the medical term for the kneecap?",{"patella","fibula","tibia","ulna"},0},
/* ------------------------------------------------------------ 1 Geography */
{1,0,"What is the capital of France?",{"Lyon","Marseille","Paris","Nice"},2},
{1,0,"Which continent is Egypt in?",{"Asia","Africa","Europe","Oceania"},1},
{1,0,"What is the longest river in the world?",{"Amazon","Nile","Yangtze","Mississippi"},1},
{1,0,"Which country is shaped like a boot?",{"Spain","Greece","Italy","Portugal"},2},
{1,0,"What is the capital of Japan?",{"Osaka","Kyoto","Tokyo","Nagoya"},2},
{1,0,"Which is the largest country by area?",{"Canada","China","USA","Russia"},3},
{1,1,"Which country has the most time zones?",{"Russia","USA","France","China"},2},
{1,1,"What is the capital of Australia?",{"Sydney","Melbourne","Canberra","Perth"},2},
{1,1,"Which sea is the saltiest?",{"Red Sea","Dead Sea","Black Sea","Caspian"},1},
{1,1,"Mount Kilimanjaro is in which country?",{"Kenya","Tanzania","Uganda","Ethiopia"},1},
{1,1,"Which strait separates Europe and Africa?",{"Bosphorus","Gibraltar","Hormuz","Malacca"},1},
{1,1,"What is the smallest country in the world?",{"Monaco","Nauru","Vatican City","San Marino"},2},
{1,2,"Which African country was never colonised?",{"Ghana","Ethiopia","Kenya","Senegal"},1},
{1,2,"The Atacama Desert is mainly in which country?",{"Peru","Bolivia","Chile","Argentina"},2},
{1,2,"Which country has the longest coastline?",{"Russia","Australia","Canada","Indonesia"},2},
{1,2,"Lake Baikal is in which country?",{"Mongolia","Russia","Kazakhstan","China"},1},
{1,2,"What is the capital of Canada?",{"Toronto","Vancouver","Montreal","Ottawa"},3},
{1,2,"Which river flows through Baghdad?",{"Euphrates","Tigris","Jordan","Orontes"},1},
{1,3,"Which country contains the most volcanoes?",{"Japan","Indonesia","USA","Chile"},1},
{1,3,"What is the deepest point in the ocean called?",{"Java Trench","Mariana Trench","Puerto Rico Trench","Tonga Trench"},1},
{1,3,"Which two countries share the longest border?",{"Russia-China","USA-Canada","Chile-Argentina","India-China"},1},
{1,3,"The Danube empties into which sea?",{"Adriatic","Baltic","Black Sea","Aegean"},2},
{1,3,"Which capital sits highest above sea level?",{"Quito","Bogota","La Paz","Kathmandu"},2},
{1,3,"Kaliningrad is an exclave of which country?",{"Poland","Lithuania","Russia","Belarus"},2},
/* -------------------------------------------------------------- 2 History */
{2,0,"Who was the first president of the USA?",{"Jefferson","Washington","Adams","Lincoln"},1},
{2,0,"In which year did World War Two end?",{"1943","1944","1945","1946"},2},
{2,0,"Which ship sank in 1912 after hitting an iceberg?",{"Lusitania","Titanic","Britannic","Olympic"},1},
{2,0,"Who built the pyramids at Giza?",{"Romans","Greeks","Egyptians","Persians"},2},
{2,0,"Which wall divided a German city until 1989?",{"Berlin Wall","Hadrian's Wall","Great Wall","Western Wall"},0},
{2,0,"Who was the queen of ancient Egypt famous for Caesar?",{"Nefertiti","Cleopatra","Hatshepsut","Isis"},1},
{2,1,"The Magna Carta was sealed in which year?",{"1066","1215","1314","1415"},1},
{2,1,"Who was the first man on the Moon?",{"Aldrin","Armstrong","Collins","Glenn"},1},
{2,1,"The Roman Empire split into how many parts in 395?",{"two","three","four","five"},0},
{2,1,"Which empire was ruled from Constantinople?",{"Ottoman","Byzantine","Persian","Mongol"},1},
{2,1,"The French Revolution began in which year?",{"1776","1789","1799","1804"},1},
{2,1,"Who wrote the Communist Manifesto with Engels?",{"Lenin","Marx","Trotsky","Bakunin"},1},
{2,2,"The Battle of Hastings was fought in which year?",{"1055","1066","1077","1088"},1},
{2,2,"Which treaty ended World War One?",{"Versailles","Utrecht","Westphalia","Vienna"},0},
{2,2,"Who was the first emperor of unified China?",{"Han Wudi","Qin Shi Huang","Kublai Khan","Sun Yat-sen"},1},
{2,2,"The Hundred Years War was between England and which country?",{"Spain","France","Scotland","Netherlands"},1},
{2,2,"Which city was destroyed by Vesuvius in AD 79?",{"Ostia","Pompeii","Ravenna","Capua"},1},
{2,2,"Who led the Carthaginians over the Alps?",{"Hamilcar","Hannibal","Hasdrubal","Scipio"},1},
{2,3,"The Rosetta Stone was found in which year?",{"1799","1822","1845","1870"},0},
{2,3,"Which dynasty preceded the Ming in China?",{"Song","Tang","Yuan","Qing"},2},
{2,3,"The Peace of Westphalia ended which war?",{"Seven Years","Thirty Years","Hundred Years","Napoleonic"},1},
{2,3,"Who was the last Tsar of Russia?",{"Alexander III","Nicholas II","Paul I","Peter III"},1},
{2,3,"The Domesday Book was compiled under which king?",{"Harold","William I","Henry I","Stephen"},1},
{2,3,"Which civilisation built Machu Picchu?",{"Maya","Aztec","Inca","Olmec"},2},
/* -------------------------------------------------------------- 3 Science */
{3,0,"What is H2O commonly called?",{"salt","water","acid","air"},1},
{3,0,"How many legs does an insect have?",{"four","six","eight","ten"},1},
{3,0,"What force pulls objects to Earth?",{"magnetism","gravity","friction","tension"},1},
{3,0,"What do plants breathe in?",{"oxygen","nitrogen","carbon dioxide","hydrogen"},2},
{3,0,"What is the centre of an atom called?",{"electron","nucleus","proton","shell"},1},
{3,0,"What state of matter is ice?",{"solid","liquid","gas","plasma"},0},
{3,1,"What is the powerhouse of the cell?",{"nucleus","ribosome","mitochondrion","vacuole"},2},
{3,1,"What is the speed of light, roughly?",{"300 km/s","3000 km/s","300000 km/s","3 million km/s"},2},
{3,1,"Which blood cells fight infection?",{"red","white","platelets","plasma"},1},
{3,1,"What is the pH of pure water?",{"0","7","10","14"},1},
{3,1,"Which scientist proposed natural selection?",{"Mendel","Darwin","Lamarck","Linnaeus"},1},
{3,1,"What particle has a negative charge?",{"proton","neutron","electron","positron"},2},
{3,2,"What is Avogadro's number, to one digit?",{"6 x 10^23","3 x 10^8","1.6 x 10^-19","9.8"},0},
{3,2,"Which law states energy cannot be created?",{"first of thermodynamics","Ohm's","Hooke's","Boyle's"},0},
{3,2,"What is the most abundant element in the universe?",{"helium","oxygen","hydrogen","carbon"},2},
{3,2,"DNA has how many strands?",{"one","two","three","four"},1},
{3,2,"What does an enzyme do to a reaction?",{"stops it","slows it","speeds it","reverses it"},2},
{3,2,"Which subatomic particle was discovered in 2012?",{"neutrino","Higgs boson","quark","muon"},1},
{3,3,"What is the half-life of carbon-14, roughly?",{"570 years","5730 years","57300 years","573 years"},1},
{3,3,"Which constant is about 6.626 x 10^-34?",{"Planck","Boltzmann","gravitational","gas"},0},
{3,3,"What is the SI unit of magnetic flux density?",{"weber","tesla","henry","gauss"},1},
{3,3,"Which process splits a heavy nucleus?",{"fusion","fission","decay","ionisation"},1},
{3,3,"What shape is a benzene molecule?",{"tetrahedral","hexagonal ring","linear","pyramidal"},1},
{3,3,"Entropy is a measure of what?",{"energy","disorder","mass","charge"},1},
/* ----------------------------------------------------------------- 4 Film */
{4,0,"Who directed Jaws?",{"Lucas","Spielberg","Scorsese","Coppola"},1},
{4,0,"Which film features a shark called Bruce off-screen?",{"Jaws","Titanic","Nemo","Deep Blue Sea"},0},
{4,0,"What colour is the Hulk?",{"blue","red","green","grey"},2},
{4,0,"Which studio made Toy Story?",{"Disney","Pixar","DreamWorks","Sony"},1},
{4,0,"Who plays Iron Man in the Marvel films?",{"Chris Evans","Robert Downey Jr","Mark Ruffalo","Chris Hemsworth"},1},
{4,0,"In which film would you find Frodo Baggins?",{"Narnia","Harry Potter","Lord of the Rings","Eragon"},2},
{4,1,"Which film won Best Picture in 1994?",{"Pulp Fiction","Forrest Gump","The Lion King","Speed"},1},
{4,1,"Who directed Pulp Fiction?",{"Tarantino","Fincher","Nolan","Coen"},0},
{4,1,"What is the highest-grossing film of all time?",{"Titanic","Avatar","Avengers Endgame","Star Wars"},1},
{4,1,"Which actor played the Joker in The Dark Knight?",{"Nicholson","Ledger","Phoenix","Leto"},1},
{4,1,"Casablanca is set during which war?",{"WWI","WWII","Korean","Vietnam"},1},
{4,1,"Who directed Inception?",{"Nolan","Villeneuve","Cameron","Ridley Scott"},0},
{4,2,"Which film opens with the line 'I believe in America'?",{"Goodfellas","The Godfather","Scarface","Casino"},1},
{4,2,"Who directed Seven Samurai?",{"Ozu","Kurosawa","Mizoguchi","Oshima"},1},
{4,2,"Which film first won Best Picture, in 1929?",{"Wings","Sunrise","The Jazz Singer","Metropolis"},0},
{4,2,"Citizen Kane's last word is what?",{"Rosebud","Mother","Home","Nothing"},0},
{4,2,"Who composed the score for Star Wars?",{"Zimmer","Williams","Horner","Morricone"},1},
{4,2,"Which director made Bicycle Thieves?",{"Fellini","De Sica","Rossellini","Visconti"},1},
{4,3,"Which film has the most Oscar wins, tied at eleven?",{"Ben-Hur","Gone with the Wind","Gandhi","Amadeus"},0},
{4,3,"Who directed Stalker and Solaris?",{"Eisenstein","Tarkovsky","Paradjanov","Klimov"},1},
{4,3,"What is the aspect ratio called at 2.39:1?",{"Academy","Scope","Flat","Vista"},1},
{4,3,"Which film pioneered bullet time?",{"Blade","The Matrix","Dark City","Equilibrium"},1},
{4,3,"Who wrote and directed Persona?",{"Bergman","Dreyer","Von Trier","Haneke"},0},
{4,3,"Which 1927 German film depicts a divided future city?",{"M","Metropolis","Nosferatu","Faust"},1},
/* ---------------------------------------------------------------- 5 Music */
{5,0,"How many keys does a standard piano have?",{"76","82","88","96"},2},
{5,0,"Which instrument has six strings usually?",{"violin","guitar","cello","harp"},1},
{5,0,"Who sang Thriller?",{"Prince","Michael Jackson","Lionel Richie","Stevie Wonder"},1},
{5,0,"How many members were in the Beatles?",{"three","four","five","six"},1},
{5,0,"What does a conductor hold?",{"bow","baton","reed","mallet"},1},
{5,0,"Which instrument is a woodwind?",{"trumpet","clarinet","violin","timpani"},1},
{5,1,"How many lines are in a musical stave?",{"four","five","six","seven"},1},
{5,1,"Which composer wrote the Fifth Symphony with four famous notes?",{"Mozart","Beethoven","Bach","Brahms"},1},
{5,1,"What tempo marking means 'fast'?",{"largo","adagio","allegro","grave"},2},
{5,1,"Which band released Dark Side of the Moon?",{"Led Zeppelin","Pink Floyd","The Who","Genesis"},1},
{5,1,"How many semitones are in an octave?",{"seven","eight","ten","twelve"},3},
{5,1,"Who composed The Four Seasons?",{"Vivaldi","Handel","Corelli","Purcell"},0},
{5,2,"What is the relative minor of C major?",{"A minor","E minor","D minor","G minor"},0},
{5,2,"Which clef is used for cello music usually?",{"treble","bass","alto","tenor"},1},
{5,2,"Who composed the opera The Magic Flute?",{"Verdi","Mozart","Wagner","Puccini"},1},
{5,2,"What does 'a cappella' mean?",{"very fast","without instruments","with strings","repeat"},1},
{5,2,"Which key has one sharp?",{"F major","G major","D major","B flat major"},1},
{5,2,"What is a group of eight musicians called?",{"sextet","septet","octet","nonet"},2},
{5,3,"Which scale has no semitones between degrees?",{"whole tone","harmonic minor","pentatonic","chromatic"},0},
{5,3,"Who composed The Rite of Spring?",{"Debussy","Stravinsky","Ravel","Bartok"},1},
{5,3,"What interval is a tritone equal to?",{"three semitones","six semitones","four semitones","eight semitones"},1},
{5,3,"Which mode starts on the fifth degree of the major scale?",{"Dorian","Phrygian","Mixolydian","Lydian"},2},
{5,3,"Who pioneered twelve-tone technique?",{"Schoenberg","Berg","Webern","Boulez"},0},
{5,3,"What is a Neapolitan sixth built on?",{"flattened supertonic","raised subdominant","lowered mediant","tonic"},0},
/* ---------------------------------------------------------------- 6 Sport */
{6,0,"How many players are on a football pitch per team?",{"nine","ten","eleven","twelve"},2},
{6,0,"What sport uses a shuttlecock?",{"tennis","squash","badminton","table tennis"},2},
{6,0,"How often are the summer Olympics held?",{"2 years","3 years","4 years","5 years"},2},
{6,0,"In which sport would you score a try?",{"cricket","rugby","hockey","netball"},1},
{6,0,"How many rings are on the Olympic flag?",{"four","five","six","seven"},1},
{6,0,"What colour card sends a footballer off?",{"yellow","red","blue","black"},1},
{6,1,"How many points is a converted try in rugby union?",{"five","six","seven","eight"},2},
{6,1,"How long is a marathon, roughly?",{"32 km","42 km","52 km","62 km"},1},
{6,1,"In tennis, what is a score of zero called?",{"nil","love","duck","blank"},1},
{6,1,"How many players in a basketball team on court?",{"four","five","six","seven"},1},
{6,1,"Which country has won the most football World Cups?",{"Germany","Italy","Brazil","Argentina"},2},
{6,1,"What is a score of three under par on a hole called?",{"birdie","eagle","albatross","condor"},2},
{6,2,"How many players are in a water polo team in the water?",{"six","seven","eight","nine"},1},
{6,2,"Which grand slam is played on clay?",{"Wimbledon","US Open","French Open","Australian Open"},2},
{6,2,"How long is an Olympic swimming pool?",{"25 m","50 m","75 m","100 m"},1},
{6,2,"In cricket, how many balls in an over?",{"four","five","six","eight"},2},
{6,2,"What is the maximum break in snooker?",{"147","155","180","200"},0},
{6,2,"How many pockets does a snooker table have?",{"four","six","eight","ten"},1},
{6,3,"Which athlete has the most Olympic gold medals?",{"Bolt","Phelps","Latynina","Lewis"},1},
{6,3,"In fencing, which weapon allows the whole body as target?",{"foil","epee","sabre","rapier"},1},
{6,3,"The Tour de France leader wears which colour?",{"green","polka dot","yellow","white"},2},
{6,3,"How many squares on a chessboard?",{"36","49","64","81"},2},
{6,3,"Which country invented judo?",{"China","Korea","Japan","Brazil"},2},
{6,3,"What is the length of a cricket pitch between wickets?",{"18 yards","20 yards","22 yards","24 yards"},2},
/* ----------------------------------------------------------- 7 Literature */
{7,0,"Who wrote Romeo and Juliet?",{"Dickens","Shakespeare","Austen","Chaucer"},1},
{7,0,"Who wrote the Harry Potter books?",{"Tolkien","Rowling","Pullman","Lewis"},1},
{7,0,"What kind of animal is Moby Dick?",{"shark","whale","squid","dolphin"},1},
{7,0,"Who wrote Oliver Twist?",{"Dickens","Hardy","Eliot","Bronte"},0},
{7,0,"In which book would you find Bilbo Baggins?",{"Narnia","The Hobbit","Dune","Watership Down"},1},
{7,0,"Who wrote Pride and Prejudice?",{"Austen","Bronte","Gaskell","Woolf"},0},
{7,1,"Who wrote Nineteen Eighty-Four?",{"Huxley","Orwell","Bradbury","Burgess"},1},
{7,1,"Which Russian wrote War and Peace?",{"Dostoevsky","Tolstoy","Chekhov","Turgenev"},1},
{7,1,"Who wrote the Discworld series?",{"Adams","Pratchett","Gaiman","Moorcock"},1},
{7,1,"What is the first book of the Bible?",{"Exodus","Genesis","Leviticus","Job"},1},
{7,1,"Who wrote Jane Eyre?",{"Charlotte Bronte","Emily Bronte","Anne Bronte","Austen"},0},
{7,1,"Which epic poem features Achilles?",{"Odyssey","Iliad","Aeneid","Beowulf"},1},
{7,2,"Who wrote One Hundred Years of Solitude?",{"Borges","Marquez","Llosa","Cortazar"},1},
{7,2,"Which novel begins 'Call me Ishmael'?",{"Moby-Dick","Billy Budd","Typee","Omoo"},0},
{7,2,"Who wrote Things Fall Apart?",{"Soyinka","Achebe","Ngugi","Gordimer"},1},
{7,2,"Ulysses by Joyce takes place over how long?",{"one day","one week","one month","one year"},0},
{7,2,"Who wrote The Waste Land?",{"Pound","Eliot","Yeats","Auden"},1},
{7,2,"Which Kafka story features a man turned insect?",{"The Trial","The Castle","Metamorphosis","Amerika"},2},
{7,3,"Who wrote In Search of Lost Time?",{"Gide","Proust","Camus","Sartre"},1},
{7,3,"Which poet wrote The Canterbury Tales?",{"Langland","Chaucer","Gower","Malory"},1},
{7,3,"Who wrote the play Waiting for Godot?",{"Ionesco","Beckett","Pinter","Genet"},1},
{7,3,"Which novel is subtitled 'The Modern Prometheus'?",{"Dracula","Frankenstein","Jekyll and Hyde","The Golem"},1},
{7,3,"Who wrote Midnight's Children?",{"Naipaul","Rushdie","Seth","Roy"},1},
{7,3,"Which Greek wrote the Theogony?",{"Homer","Hesiod","Pindar","Sappho"},1},
{0,0,NULL,{NULL,NULL,NULL,NULL},0}
};

const int QUIZ_BANK_COUNT = (int)(sizeof(QUIZ_BANK) / sizeof(QUIZ_BANK[0])) - 1;
