/* registry.c - maps family names to their engines.
 * A catalogue entry is playable exactly when its family appears here,
 * so each new batch of engines lights up its entries automatically.
 */
#include "engine.h"
#include "games.h"

const FamilyEntry FAMILY_REGISTRY[] = {
    {"tictactoe",          fam_tictactoe},
    {"connect",            fam_connect4},
    {"reversi",            fam_reversi},
    {"gomoku",             fam_gomoku},
    {"checkers",           fam_checkers},
    {"mancala",            fam_mancala},
    {"nim",                fam_nim},
    {"dotsboxes",          fam_dots_boxes},
    {"battleship",         fam_battleship},
    {"mastermind",         fam_mastermind},
    {"minesweeper",        fam_minesweeper},
    {"sudoku",             fam_sudoku},
    {"sliding",            fam_fifteen},
    {"lightsout",          fam_lights_out},
    {"floodit",            fam_flood_it},
    {"sokoban",            fam_sokoban},
    {"memory",             fam_memory},
    {"merge",              fam_2048},
    {"hanoi",              fam_hanoi},
    {"nonogram",           fam_nonogram},
    {"snake",              fam_snake},
    {"tetris",             fam_tetris},
    {"pong",               fam_pong},
    {"breakout",           fam_breakout},
    {"invaders",           fam_invaders},
    {"dino",               fam_dino},
    {"flappy",             fam_flappy},
    {"frogger",            fam_frogger},
    {"pacman",             fam_pacman},
    {"asteroids",          fam_asteroids},
    {"blackjack",          fam_blackjack},
    {"videopoker",         fam_video_poker},
    {"war",                fam_war},
    {"gofish",             fam_go_fish},
    {"yahtzee",            fam_yahtzee},
    {"pig",                fam_pig},
    {"slots",              fam_slots},
    {"higherlower",        fam_higher_lower},
    {"hangman",            fam_hangman},
    {"wordle",             fam_wordle},
    {"anagram",            fam_anagram},
    {"typing",             fam_typing},
    {"guessnumber",        fam_guess_number},
    {"bullscows",          fam_bulls_cows},
    {"rps",                fam_rps},
    {"simon",              fam_simon},
    {"snakesladders",      fam_snakes_ladders},
    {"dungeon",            fam_dungeon},
    {"piano",              fam_piano},
    {"maze",               fam_maze},
    {"quiz",               fam_quiz},
    {"constraint",         fam_constraint},
    {"pegsolitaire",       fam_pegsolitaire},
    {"matchthree",         fam_matchthree},
    {"wordsearch",         fam_wordsearch},
};

const int FAMILY_REGISTRY_COUNT =
    (int)(sizeof(FAMILY_REGISTRY) / sizeof(FAMILY_REGISTRY[0]));
